### ISSUE TITLE
环境配置问题

### ISSUE THREAD

**Issue by freshcold** [Choise-ieee/Yolov11-onnx_cpp#1]
请问你这里的opencv和onnxruntime用的什么版本

**Comment by Choise-ieee** [comment]
没有用到opencv 直接用的onnxrunningtime
main.cpp里面有提到有old和new的版本 1.14以上和1.14以下onnx的有区别

**Comment by Choise-ieee** [comment]
> 请问你这里的opencv和onnxruntime用的什么版本

没有用到opencv 直接用的onnxrunningtime
main.cpp里面有提到有old和new的版本 1.14以上和1.14以下onnx的有区别

**Comment by freshcold** [comment]
谢谢你的回复，我已经跑通了，感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Choise-ieee/Yolov11-onnx_cpp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月10日(星期天) 中午1:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Choise-ieee/Yolov11-onnx_cpp] 环境配置问题 (Issue #1)





 
没有用到opencv 直接用的onnxrunningtime
 main.cpp里面有提到有old和new的版本 1.14以上和1.14以下onnx的有区别

**Comment by Choise-ieee** [comment]
okok
是的 就是care有的对onnx的版本升级之后的api不熟悉 所以专门写了注释
